/** Generated by mndsite CLI — do not edit */
module.exports = {
  title: "mndsite",
  repo_url: "https://github.com/kotulc/nlp-mndsite",
  feed_url: "updates",
  description: "Static documentation sites from plain markdown",
  footer: "",
  theme_toggle: "navbar",
  toc: true,
  reading_time: true,
  theme: {"color":"default","typeset":"sans","navbar":"","footer":"","hue":{"light":212,"dark":204},"saturation":100,"font_stack":""},
  nav_order: {"":["about","getting-started","configuration"],"features":["overview","components"],"specifications":["format"],"updates":["welcome"]},
}
