/** Generated by mndsite CLI — do not edit */
module.exports = {
  title: "mndsite",
  repo_url: "https://github.com/kotulc/mndsite",
  feed_url: "updates",
  description: "Static documentation sites from plain markdown",
  footer: "",
  theme_toggle: "navbar",
  theme: {"color":"default","typeset":"sans","navbar":"","footer":"","hue":{"light":212,"dark":204},"saturation":100,"font_stack":""},
  nav_order: {"":["about","getting-started","configuration"],"features":["overview","components"],"specifications":["format"],"updates":["welcome"]},
  fields: {"title":"title","description":["description","desc"],"date":"date","reading_time":"reading_time","related":"related","identity":"doc_id"},
  facets: {"categories":{"field":"categories","label":"Category","color":"blue","ui":"chips","sort":"alpha","hue":210},"tags":{"field":"tags","label":"Tag","color":"violet","ui":"chips","sort":"alpha","hue":265}},
  collections: {"default":"all"},
  sidebar: {"views":["tree"]},
  display: {"title_row":["info","contents"],"header":["date","reading_time","facets"],"info":["description"],"toc":["sections","related","edit"],"navbar":["theme","feed","github"]},
  limits: {"header_chips":8,"related":6},
  edit: {"branch":"main","path":"docs","url":"{repo_url}/edit/{branch}/{file}"},
}
