/**
 * YAML config loader for the mdsite CLI.
 * Reads mdsite.yaml, validates required fields, applies defaults, and generates
 * site.config.js so Next.js and Nextra can consume the config at build time.
 */
const fs   = require('fs')
const path = require('path')
const yaml = require('js-yaml')
const { resolve_theme } = require('./theme')


const DEFAULTS = {
  repo_url:       '',
  feed_url:       '',
  description:    '',
  footer:         '',
  theme_toggle:   'navbar',
  toc:            true,
  reading_time:   true,
  theme:          { color: 'default', typeset: 'sans', navbar: '', footer: '' },
  tags:           {
    max_keywords: 32,
    page_tags: 5,
    top_n_related: 3,
  },
  flatten:        [],
  nav_order:      {},
  content:        './docs',
  output:         './dist',
  components:     '',
  assets:         '',
}


function load_config(yaml_path) {
  /** Read and parse a YAML config file; resolve content/output relative to its directory. */
  const abs  = path.resolve(yaml_path)
  const dir  = path.dirname(abs)
  const raw  = yaml.load(fs.readFileSync(abs, 'utf8'))
  const cfg  = { ...DEFAULTS, ...raw }

  if (!cfg.title) throw new Error(`mdsite.yaml: 'title' is required`)

  cfg.theme = resolve_theme({ ...DEFAULTS.theme, ...(raw.theme || {}) })
  cfg.tags  = resolve_tags(raw.tags)

  cfg.content = path.resolve(dir, cfg.content)
  cfg.output  = path.resolve(dir, cfg.output)
  if (cfg.components) cfg.components = path.resolve(dir, cfg.components)
  if (cfg.assets)     cfg.assets     = path.resolve(dir, cfg.assets)

  return cfg
}


function resolve_tags(raw) {
  /** Merge the tags block over defaults. Fixed groups live in scripts/meta.js. */
  const cfg = { ...DEFAULTS.tags, ...(raw || {}) }
  cfg.max_keywords  = parseInt(cfg.max_keywords, 10)
  cfg.page_tags     = parseInt(cfg.page_tags, 10)
  cfg.top_n_related = parseInt(cfg.top_n_related, 10)
  if (!(cfg.max_keywords > 0)) throw new Error(`mdsite.yaml: tags.max_keywords must be a positive integer`)
  if (!(cfg.page_tags > 0))    throw new Error(`mdsite.yaml: tags.page_tags must be a positive integer`)
  if (cfg.top_n_related < 0 || Number.isNaN(cfg.top_n_related)) {
    throw new Error(`mdsite.yaml: tags.top_n_related must be a non-negative integer`)
  }
  return cfg
}


function write_site_config(config, dest_dir) {
  /** Generate site.config.js from a config object for Next.js/Nextra consumption. */
  const dir  = dest_dir || path.join(__dirname, '..')
  const keys = [
    'title', 'repo_url', 'feed_url', 'description', 'footer',
    'theme_toggle', 'toc', 'reading_time',
    'theme', 'flatten', 'nav_order',
  ]
  const values = {
    ...Object.fromEntries(keys.map(k => [k, config[k]])),
    page_tags: config.tags.page_tags,
  }
  const body = Object.entries(values)
    .map(([k, v]) => `  ${k}: ${JSON.stringify(v)}`)
    .join(',\n')

  fs.writeFileSync(
    path.join(dir, 'site.config.js'),
    `/** Generated by mdsite CLI — do not edit */\nmodule.exports = {\n${body},\n}\n`
  )
}


module.exports = { load_config, write_site_config, DEFAULTS }
