/**
 * YAML config loader for the mndsite CLI.
 * Reads mndsite.yaml, validates required fields, applies defaults, and generates
 * site.config.js so Next.js and Nextra can consume the config at build time.
 */
const fs   = require('fs')
const path = require('path')
const yaml = require('js-yaml')
const { resolve_theme } = require('./theme')


const REMOVED_KEYS = {
  meta: 'Move tagging and related-link configuration upstream to mndmap or frontmatter.',
  flatten: 'Move directory organization upstream to mndmap.',
}


const DEFAULTS = {
  repo_url:       '',
  feed_url:       '',
  description:    '',
  footer:         '',
  theme_toggle:   'navbar',
  toc:            true,
  reading_time:   true,
  theme:          { color: 'default', typeset: 'sans', navbar: '', footer: '' },
  nav_order:      {},
  content:        './docs',
  output:         './dist',
  components:     '',
  assets:         '',
}


function reject_removed_keys(raw) {
  for (const [key, hint] of Object.entries(REMOVED_KEYS)) {
    if (raw && Object.prototype.hasOwnProperty.call(raw, key)) {
      throw new Error(`mndsite.yaml: '${key}' is no longer supported. ${hint}`)
    }
  }
}


function load_config(yaml_path) {
  const abs  = path.resolve(yaml_path)
  const dir  = path.dirname(abs)
  const raw  = yaml.load(fs.readFileSync(abs, 'utf8'))
  reject_removed_keys(raw)
  const cfg  = { ...DEFAULTS, ...raw }

  if (!cfg.title) throw new Error(`mndsite.yaml: 'title' is required`)

  cfg.theme = resolve_theme({ ...DEFAULTS.theme, ...(raw.theme || {}) })

  cfg.content = path.resolve(dir, cfg.content)
  cfg.output  = path.resolve(dir, cfg.output)
  if (cfg.components) cfg.components = path.resolve(dir, cfg.components)
  if (cfg.assets)     cfg.assets     = path.resolve(dir, cfg.assets)

  return cfg
}


function write_site_config(config, dest_dir) {
  const dir  = dest_dir || path.join(__dirname, '..')
  const keys = [
    'title', 'repo_url', 'feed_url', 'description', 'footer',
    'theme_toggle', 'toc', 'reading_time',
    'theme', 'nav_order',
  ]
  const values = Object.fromEntries(keys.map(k => [k, config[k]]))
  const body = Object.entries(values)
    .map(([k, v]) => `  ${k}: ${JSON.stringify(v)}`)
    .join(',\n')

  fs.writeFileSync(
    path.join(dir, 'site.config.js'),
    `/** Generated by mndsite CLI — do not edit */\nmodule.exports = {\n${body},\n}\n`
  )
}


module.exports = { load_config, write_site_config, DEFAULTS, REMOVED_KEYS }
